import { CountryOption, Provider, ComplianceRule } from '../types';

export const SUPPORTED_COUNTRIES: CountryOption[] = [
  { code: 'US', name: 'United States', flag: '🇺🇸', currency: 'USD', currencySymbol: '$' },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪', currency: 'AED', currencySymbol: 'AED ' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', currency: 'GBP', currencySymbol: '£' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', currency: 'CAD', currencySymbol: 'C$' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺', currency: 'AUD', currencySymbol: 'A$' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬', currency: 'SGD', currencySymbol: 'S$' },
  { code: 'IN', name: 'India', flag: '🇮🇳', currency: 'INR', currencySymbol: '₹' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭', currency: 'PHP', currencySymbol: '₱' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽', currency: 'MXN', currencySymbol: 'Mex$' },
];

export const LIVE_TICKER_PAIRS = [
  { pair: 'AED → INR', rate: '23.42', change: '+0.15%', isUp: true },
  { pair: 'USD → INR', rate: '87.31', change: '-0.08%', isUp: false },
  { pair: 'GBP → INR', rate: '118.22', change: '+0.42%', isUp: true },
  { pair: 'CAD → INR', rate: '63.44', change: '-0.12%', isUp: false },
  { pair: 'AUD → INR', rate: '56.90', change: '+0.28%', isUp: true },
  { pair: 'SGD → INR', rate: '65.18', change: '+0.10%', isUp: true },
  { pair: 'USD → PHP', rate: '58.45', change: '+0.05%', isUp: true },
  { pair: 'USD → MXN', rate: '18.12', change: '-0.30%', isUp: false },
];

export const INITIAL_PROVIDERS: Provider[] = [
  {
    id: 'wise',
    name: 'Wise',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=120&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewCount: 142000,
    transferSpeed: '2 Hours (Same Day)',
    estimatedHours: 2,
    exchangeRate: 87.25,
    fee: 3.5,
    fxMarkup: 0.1,
    deliveryMethods: ['Bank Account', 'UPI Direct', 'Mobile Wallet'],
    paymentMethods: ['Debit Card', 'Bank Transfer (ACH)', 'Credit Card'],
    pros: ['Zero exchange rate markup', 'Real-time UPI speed', 'Transparent mid-market rate'],
    cons: ['Slightly higher fee for credit cards'],
    badges: ['Cheapest Overall', 'Lowest Fees', 'AI Verified'],
    isRecommended: true,
  },
  {
    id: 'remitly',
    name: 'Remitly',
    logo: 'https://images.unsplash.com/photo-1628155930542-3c7a64e2c833?w=120&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewCount: 98000,
    transferSpeed: 'Minutes (Express)',
    estimatedHours: 0.1,
    exchangeRate: 86.90,
    fee: 0.0,
    fxMarkup: 0.45,
    deliveryMethods: ['Bank Account', 'Cash Pickup', 'UPI', 'Mobile Wallet'],
    paymentMethods: ['Debit Card', 'Credit Card'],
    pros: ['Zero upfront transfer fee for Express', 'Instant cash pickup points'],
    cons: ['Exchange rate includes slight markup'],
    badges: ['Fastest Express', 'Zero Fee First Transfer'],
  },
  {
    id: 'western_union',
    name: 'Western Union',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=120&auto=format&fit=crop&q=80',
    rating: 4.3,
    reviewCount: 210000,
    transferSpeed: 'Minutes - 1 Day',
    estimatedHours: 0.2,
    exchangeRate: 86.40,
    fee: 4.99,
    fxMarkup: 0.95,
    deliveryMethods: ['Bank Account', 'Cash Pickup', 'Agent Location'],
    paymentMethods: ['Cash', 'Debit Card', 'Bank Transfer'],
    pros: ['500,000+ global agent locations', 'Cash payment accepted'],
    cons: ['Higher exchange rate markup', 'Higher transaction fees'],
    badges: ['Most Agent Locations'],
  },
  {
    id: 'xe',
    name: 'XE Money Transfer',
    logo: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=120&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewCount: 54000,
    transferSpeed: '1 - 3 Days',
    estimatedHours: 24,
    exchangeRate: 86.80,
    fee: 2.0,
    fxMarkup: 0.5,
    deliveryMethods: ['Bank Account'],
    paymentMethods: ['Wire Transfer', 'Direct Debit'],
    pros: ['High transfer limit support', 'Reliable corporate transfers'],
    cons: ['Slower delivery speed', 'No cash pickup options'],
    badges: ['Best for Large Sums'],
  },
  {
    id: 'al_ansari',
    name: 'Al Ansari Exchange',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=120&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewCount: 38000,
    transferSpeed: 'Minutes - 1 Day',
    estimatedHours: 1,
    exchangeRate: 23.40,
    fee: 15.0, // AED
    fxMarkup: 0.35,
    deliveryMethods: ['Bank Account', 'Cash Pickup', 'Instant Credit'],
    paymentMethods: ['Branch Cash', 'PayPlus Card', 'Online Transfer'],
    pros: ['Dominant GCC corridor leader', 'Physical branch network'],
    cons: ['Primarily AED corridors'],
    badges: ['GCC Specialist'],
  },
];

export const COMPLIANCE_RULES: Record<string, ComplianceRule> = {
  IN: {
    countryCode: 'IN',
    countryName: 'India',
    currency: 'INR',
    flag: '🇮🇳',
    kycRequired: true,
    amlCheck: true,
    sanctionsScreening: true,
    riskLevel: 'Low',
    maxDailyLimit: 250000, // USD equivalent under LRS / RDA
    regulatoryBody: 'Reserve Bank of India (RBI)',
    notes: 'Inward remittances under Rupee Drawing Arrangement (RDA) are capped at ₹15,00,000 per transaction for personal transfers.',
    requiredDocuments: [
      { name: 'Government-Issued Photo ID', description: 'Passport, Aadhaar Card, or Voter ID of receiver', mandatory: true },
      { name: 'PAN Card (Permanent Account Number)', description: 'Mandatory for transactions above ₹50,000', mandatory: true },
      { name: 'Recipient Bank Account & IFSC', description: 'Mandatory for direct bank & UPI settlement', mandatory: true },
      { name: 'Purpose Code of Transfer', description: 'Categorization (Family Maintenance, Education, Savings)', mandatory: true },
    ],
  },
  US: {
    countryCode: 'US',
    countryName: 'United States',
    currency: 'USD',
    flag: '🇺🇸',
    kycRequired: true,
    amlCheck: true,
    sanctionsScreening: true,
    riskLevel: 'Low',
    maxDailyLimit: 10000,
    regulatoryBody: 'FinCEN / Consumer Financial Protection Bureau (CFPB)',
    notes: 'Transfers above $10,000 trigger mandatory FinCEN CTR (Currency Transaction Report) filing.',
    requiredDocuments: [
      { name: 'US Drivers License / Passport', description: 'State-issued photo identification', mandatory: true },
      { name: 'SSN / ITIN Verification', description: 'Social Security Number for identity matching', mandatory: true },
      { name: 'Proof of Address', description: 'Utility bill or bank statement within 90 days', mandatory: false },
    ],
  },
  AE: {
    countryCode: 'AE',
    countryName: 'United Arab Emirates',
    currency: 'AED',
    flag: '🇦🇪',
    kycRequired: true,
    amlCheck: true,
    sanctionsScreening: true,
    riskLevel: 'Low',
    maxDailyLimit: 50000,
    regulatoryBody: 'Central Bank of the UAE (CBUAE)',
    notes: 'Emirates ID card mandatory for all digital and over-the-counter money transfers.',
    requiredDocuments: [
      { name: 'Emirates ID Card', description: 'Valid UAE residency card', mandatory: true },
      { name: 'Passport with UAE Residency Visa', description: 'Required for non-nationals', mandatory: true },
      { name: 'Source of Funds Declaration', description: 'Required for transfers > 55,000 AED', mandatory: false },
    ],
  },
  GB: {
    countryCode: 'GB',
    countryName: 'United Kingdom',
    currency: 'GBP',
    flag: '🇬🇧',
    kycRequired: true,
    amlCheck: true,
    sanctionsScreening: true,
    riskLevel: 'Low',
    maxDailyLimit: 20000,
    regulatoryBody: 'Financial Conduct Authority (FCA)',
    notes: 'Strict KYC verification under MLR 2017 regulatory framework.',
    requiredDocuments: [
      { name: 'UK Passport or Driving Licence', description: 'Government issued photo ID', mandatory: true },
      { name: 'Proof of UK Address', description: 'Bank statement or council tax bill', mandatory: true },
    ],
  },
  CA: {
    countryCode: 'CA',
    countryName: 'Canada',
    currency: 'CAD',
    flag: '🇨🇦',
    kycRequired: true,
    amlCheck: true,
    sanctionsScreening: true,
    riskLevel: 'Low',
    maxDailyLimit: 10000,
    regulatoryBody: 'FINTRAC',
    notes: 'Transactions over 10,000 CAD are automatically reported to FINTRAC.',
    requiredDocuments: [
      { name: 'Canadian Passport / Drivers Licence', description: 'Government photo ID', mandatory: true },
      { name: 'SIN (Social Insurance Number)', description: 'Optional unless requested for AML check', mandatory: false },
    ],
  },
};
